### ISSUE TITLE
[BUG] PostgreSQL AssertionError database connection isn't set to UTC

### ISSUE THREAD

**Issue by Archarachne** [graphite-project/docker-graphite-statsd#215]
So I was trying to put a custom docker image with local_settings.py file and a PostgreSQL database and am getting the above assertion error. This error is connected to psycopg2 version being above 2.8 so I did the following:

Dockerfile

```
FROM graphiteapp/graphite-statsd:1.1.10-3

ADD graphite/local_settings.py /opt/graphite/webapp/graphite/
ENV PYTHONPATH="/opt/graphite/lib/:/opt/graphite/webapp/"

RUN apk update
RUN apk add python3-dev py3-pip postgresql-dev gcc musl-dev
RUN pip install --upgrade pip
RUN pip install psycopg2==2.8.6 psycopg2-binary==2.8.6
```

local_settings.py
```
DATABASES = {
   'default': {
       'NAME': 'graphite',
       'ENGINE': 'django.db.backends.postgresql_psycopg2',
       'USER': 'graphite',
       'PASSWORD': 'graphite',
       'HOST': 'graphite-db',
       'PORT': '5432'
   }
}

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = False
```

stackfile.yml
```
volumes:
  graphite_storage: {}
  graphite_storage_statsd: {}
  graphite_postgres_data: {}
  
services:
  graphite-db:
    image: postgres:14
    networks:
      - monitoring
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: graphite
      POSTGRES_PASSWORD: graphite
      POSTGRES_USER: graphite
    volumes:
      - graphite_postgres_data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all" ]
    deploy:
      <<: *standard-deploy-policy
      <<: *constraint-monitoring-storage-node
      mode: replicated
      replicas: 1

  graphite:
    build:
      context: .
      dockerfile: Dockerfile-graphite
    ports:
      - "8080:8080"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - graphite_storage:/opt/graphite/storage
      - graphite_storage_statsd:/opt/statsd
    networks:
      - monitoring
 networks:
  monitoring:
    attachable: true
```

docker-compose up starts up fine, migration goes through, /admin/login/ lets you in with defaults and then breaks with the assertion error.

Is it a bug, am I missing something in the Dockerfile or settings file?

<img width="1030" alt="Screenshot 2022-11-02 at 14 29 17" src="https://user-images.githubusercontent.com/1681802/199502022-c4c6944b-2202-49dd-8d87-ed0dae4975ed.png">
