### ISSUE TITLE
[BUG] StatsD won't work with TCP even if STATSD_INTERFACE=tcp

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [graphite-project/docker-graphite-statsd#216]
**Describe the bug**

* I created a `docker-compose.yaml` to run the `graphiteapp/graphite-statsd:1.1.10-3` docker image.
* I run all configuration default, **except one** : i wanted `statsd` to use TCP instead of UDP, so I set `STATSD_INTERFACE=tcp`
* with the exact same configuration, but setting  `STATSD_INTERFACE=udp`, I can successfully  [send some stats to `statsd` using `netcat`](https://github.com/graphite-project/docker-graphite-statsd#send-some-stats) : I can see a curve appearing at http://${GRAPHITE_DNSNAME}/render?from=-10mins&until=now&target=stats.example
* As you have guessed,  when I set `STATSD_INTERFACE=tcp`, whatever netcat command i may try, nothing happens, no data appears http://${GRAPHITE_DNSNAME}/render?from=-10mins&until=now&target=stats.example

**To Reproduce**

* UDP or TCP, i both tried the exact same test "from within the container" : 

```bash
export CONTAINER_NAME="graphite-statsd-graphite1-1"
# docker exec -it ${CONTAINER_NAME} sh -c 'nc --help'

for UNUSED_VARIABLE in {1..25}
do
    export EXAMPLE_TO_SEND="example:$((RANDOM % 100))|c"
    echo " EXAMPLE_TO_SEND=[${EXAMPLE_TO_SEND}] "
    docker exec -it ${CONTAINER_NAME} sh -c "echo -n \"${EXAMPLE_TO_SEND}\" | nc -u -w 1 -vv 0.0.0.0 8125"
done

```

* Same but from outside container, works too _"in UDP mode"_, but not _"in TCP mode"_ : 

```bash
for UNUSED_VARIABLE in {1..15}
do
    export EXAMPLE_TO_SEND="example:$((RANDOM % 100))|c"
    echo " EXAMPLE_TO_SEND=[${EXAMPLE_TO_SEND}] "
    echo -n "${EXAMPLE_TO_SEND}" | nc -u -w 1 -vv ${GRAPHITE_DNSNAME} 8125
done

```
* My docker-compose : 

```Yaml
# ---
# 
version: '3.7'
# --
x-graphite-common: &graphite-common
  image: graphiteapp/graphite-statsd:${GRAPHITE_DOCKER_TAG}
  # user: "${POKUS_LX_USER_UID_GID}"
  user: root
  ports:
    - "${GRAPHITE_IP_ADDR}:80:80"
    - "${GRAPHITE_IP_ADDR}:2003-2004:2003-2004"
    - "${GRAPHITE_IP_ADDR}:2023-2024:2023-2024"
    # --- 
    # For developer testing local stack for
    # lighthouse/sitespeed.io, i will use TCP instead of UDP : 
    # though a little slower, i prefer network traffic to
    # be controlled and return appropriate errors if network
    # connections are to be debugged
    # --- 
    # - "${GRAPHITE_IP_ADDR}:8125:8125/udp"
    - "${GRAPHITE_IP_ADDR}:8125:8125/tcp"
    - "${GRAPHITE_IP_ADDR}:8126:8126"
  env_file:
    # in the env file i have STATSD_INTERFACE=tcp or STATSD_INTERFACE=udp
    - ./.graphite.env
  volumes: 
    # - graphite_conf_Data:/opt/graphite/conf 
    # https://github.com/graphite-project/docker-graphite-statsd/blob/0b273187a16ddf1bdee795dc244c717cab9c3354/docker-compose.yml#L10
    - $PWD/conf/opt/graphite/conf:/opt/graphite/conf
    # - graphite_storage_Data:/opt/graphite/storage 
    # - graphite_custom_functions_Data:/opt/graphite/webapp/graphite/functions/custom 
    # - graphite_nginx_Data:/etc/nginx 
    # - graphite_statsd_config_Data:/opt/statsd/config 
    - $PWD/conf/opt/statsd/conf:/opt/statsd/config
    # - graphite_logrotate_Data:/etc/logrotate.d 
    # - graphite_log_Data:/var/log 
    # - graphite_redis_Data:/var/lib/redis
  # ------ # 
  # 8080 in container : Graphite internal gunicorn port (without Nginx proxying).
  #   + https://graphite.readthedocs.io/en/stable/install.html
  #   + https://graphite.readthedocs.io/en/stable/metrics_api.html#metrics-index-json
  # ----
  healthcheck:
    # ---
    # curl -sfo /dev/null http://localhost:8080/metrics/index.json
    # ---
    # image does not have curl, so i use wget instead :
    # ---
    test: ["CMD", "wget", "-o", "/dev/null", "--spider", "-q", "http://localhost:8080/metrics/index.json"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  graphite1:
    <<: *graphite-common
    hostname: graphite1
    restart: unless-stopped


## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  # /opt/graphite/conf # $PWD/conf/opt/graphite/conf:/opt/graphite/conf
  # graphite_conf_Data:
  # /opt/graphite/storage
  graphite_storage_Data:
  # /opt/graphite/webapp/graphite/functions/custom
  graphite_custom_functions_Data:
  # /etc/nginx
  graphite_nginx_Data:
  # /opt/statsd/config # $PWD/conf/opt/statsd/conf:/opt/statsd/config
  # graphite_statsd_config_Data:
  # /etc/logrotate.d
  graphite_logrotate_Data:
  # /var/log
  graphite_log_Data:
  # /var/lib/redis
  graphite_redis_Data:

```

**Expected behavior**
<! -- A clear and concise description of what you expected to happen. -->

That in TCP mode, the result is same than in UDP mode.

**Environment (please complete the following information):**
 

* OS : Debian 11
*  `graphiteapp/graphite-statsd:1.1.10-3` docker image
* about **custom volumes**, see `docker-compose.yaml` above, and : 
  * The `tcp.js` and `udp.js` are used unchanged, as you provide them in this repository
  * In the `/opt/graphite/conf` all the configuration files are used unchanged, as you provide them in this repository

* `udp.js` : 
```JavaScript
{
  "graphiteHost": "127.0.0.1",
  "graphitePort": 2003,
  "port": 8125,
  "flushInterval": 10000,
  "servers": [
    { server: "./servers/udp", address: "0.0.0.0", port: 8125 }
  ]
}
```
* `tcp.js` : 
```JavaScript
{
  "graphiteHost": "127.0.0.1",
  "graphitePort": 2003,
  "port": 8125,
  "flushInterval": 10000,
  "servers": [
    { server: "./servers/tcp", address: "0.0.0.0", port: 8125 }
  ]
}
```

**Additional context**

Just to make sure,  _"in TCP mode"_, I checked the networking : 

```bash
$ export CONTAINER_NAME="graphite-statsd-graphite1-1"
$ docker exec -it ${CONTAINER_NAME} sh -c 'netstat -tulpn'
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:2003            0.0.0.0:*               LISTEN      99/python3
tcp        0      0 127.0.0.11:35859        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:2004            0.0.0.0:*               LISTEN      99/python3
tcp        0      0 0.0.0.0:7002            0.0.0.0:*               LISTEN      99/python3
tcp        0      0 0.0.0.0:8125            0.0.0.0:*               LISTEN      1753/tcp.js
tcp        0      0 0.0.0.0:2023            0.0.0.0:*               LISTEN      98/python3
tcp        0      0 0.0.0.0:2024            0.0.0.0:*               LISTEN      98/python3
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      73/python3
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      69/nginx.conf
tcp        0      0 :::8126                 :::*                    LISTEN      1753/tcp.js
udp        0      0 0.0.0.0:60868           0.0.0.0:*                           73/python3
udp        0      0 127.0.0.11:44573        0.0.0.0:*                           -

```

* Note that, in the logs above, we can see that in container: 
  * `carbon` is indeed, listening on port `2003`, bound to `0.0.0.0` network interface (see below the `99/python3` line).
  * `statsd` is indeed, listening on port `8125`, bound to `0.0.0.0` network interface (see below the `1753/tcp.js` line).
  * nginx is indeed, listening on port `80`, bound to `0.0.0.0` network interface (see below the `69/nginx.conf` line).
* As you can also see below, all those container port numbers are indeed mapped (by my docker-compose) to external ports (so they indedd, are reachable from outside container) : 

```bash
$ docker ps -a | grep graphite
ee36827d4a17   graphiteapp/graphite-statsd:1.1.10-3               "/entrypoint"            24 minutes ago   Up 24 minutes (healthy)    192.168.31.117:80->80/tcp, 192.168.31.117:2003-2004->2003-2004/tcp, 2013-2014/tcp, 192.168.31.117:2023-2024->2023-2024/tcp, 192.168.31.117:8125-8126->8125-8126/tcp, 8080/tcp, 8125/udp   graphite-statsd-graphite1-1

```
