### ISSUE TITLE
Multiple carbon-cache instances don't work

### ISSUE THREAD

**Issue by ravbaba** [graphite-project/docker-graphite-statsd#86]
I'v been trying to add an extra carbon-cache instance but it looks like this repo supports only one carbon-cache. I added this to `carbon.conf` file:

```
[cache:b]
LINE_RECEIVER_PORT = 2103
PICKLE_RECEIVER_PORT = 2104
CACHE_QUERY_PORT = 7102
```
and this to relay section

```
DESTINATIONS = 127.0.0.1:2004:a, 127.0.0.1:2104:b
```
here is my `docker-compose.yaml` file

```
version: '2'
services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    volumes:
      - ./conf:/opt/graphite/conf
      - ./storage:/opt/graphite/storage
    environment:
      RELAY: 1
      GRAPHITE_CARBONLINK_HOSTS: "127.0.0.1:7002:a, 127.0.0.1:7102:b"
    ports:
      - "80:80"
      - "81:81"
      - "2003-2004:2003-2004"
      - "2103-2104:2103-2104"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
```
that what `docker-compose logs -f graphite` shows:

```
graphite    | 07/02/2019 10:56:41 :: [clients] Destination is down: 127.0.0.1:2104:b (4/5)
graphite    | 07/02/2019 10:56:41 :: [console] Stopping factory CarbonClientFactory(127.0.0.1:2104:b)
graphite    | 07/02/2019 10:56:41 :: [console] Starting factory CarbonClientFactory(127.0.0.1:2104:b)
graphite    | 07/02/2019 10:56:41 :: [clients] CarbonClientFactory(127.0.0.1:2104:b)::startedConnecting (127.0.0.1:2104)
graphite    | 07/02/2019 10:56:41 :: [console] <twisted.internet.tcp.Connector object at 0x7f4653f5b3c8> will retry in 4 seconds
graphite    | 07/02/2019 10:56:41 :: [clients] CarbonClientFactory(127.0.0.1:2104:b)::clientConnectionFailed (127.0.0.1:2104) Connection was refused by other side: 111: Connection refused.
```
I think there should be a way to run all `carbon-cache` instances defined in `carbon.conf` file

example how to run a specific instance:

`python3 /opt/graphite/bin/carbon-cache.py --instance=b start`

Sorry if I am wrong and I missed something.
